Rust rewrite
John123Allison/hackpack-bot pull request #21
Opened 2021-09-29 21:49 UTC by weakphish

2021-09-29 22:01 UTC, quantatic requested changes
Needs a better description + title, but otherwise good.

2021-10-01 14:07 UTC, tcheinen commented
clippy-check doesn't succeed bc https://github.com/LoliGothick/clippy-check/blob/4049a639d768d98ffa02ec935cedaa8ea6284904/src/main.ts#L42 ; looks like a typo

2021-10-01 17:08 UTC, tsheinen commented on src/main.rs
> +    let application_id: u64 = env::var("APPLICATION_ID")
i don't think it'll be particularly problematic but in theory we leak secrets to child processes this way

2021-10-01 17:08 UTC, tsheinen commented on src/main.rs
> +    async fn register_command(
we only get 200 of these a day so registering it in individual guilds doesn't scale; I think it would be better to do it manually using global commands (or guild level commands when testing)

2021-10-01 17:08 UTC, tsheinen commented on src/main.rs
> +            for application_command in APPLICATION_COMMANDS {
probably premature optimization but oof ow linear and i think we can beat this. i have some macro fuckery percolating in my mind to generate a match statement (need to double check if that compiles to a lookup table) or alternatively we could just make a map lol. [phf](https://docs.rs/phf/0.10.0/phf/) gives us compile time generated maps or we could just generate it at runtime

2021-10-01 17:08 UTC, tsheinen commented on src/main.rs
> +            for application_command in APPLICATION_COMMANDS {
nevermind nathan says matching over strings is fast

2021-10-01 17:18 UTC, weakphish commented on src/main.rs
> +            for application_command in APPLICATION_COMMANDS {
oof ouch ow my linear bones

2021-10-01 17:25 UTC, quantatic commented on src/main.rs
> +            for application_command in APPLICATION_COMMANDS {
Doesn't using a map with O(1) lookup still give us linear time over the length of the string anyways (plus worse performance in the optimal case where strings diverge early or are a different length)? Hashing still means we need to do, at a minimum, about as much work as a simple string comparison. We're paying some overhead here for dynamic dispatch, but that's the price of concise code 😉

2021-10-01 17:31 UTC, ProfDoof commented on src/main.rs
> +            for application_command in APPLICATION_COMMANDS {
Depends on the implementation of the map. And you're also forgetting that if you're going to consider it that way, you have a O(mn) runtime for this algorithm whereas we would have a O(mlogn) for a map instead. (Also, maps are only average O(1) they are typically O(logn) or O(n))

2021-10-01 17:34 UTC, quantatic commented on src/main.rs
> +            for application_command in APPLICATION_COMMANDS {
Oh oops you're totally right, I was thinking you were referring to something totally different here. Ignore my comment above, I must have been looking at the wrong bit of code.

2021-10-03 02:19 UTC, quantatic approved these changes

2021-10-03 03:11 UTC, merged